Задача "Добавление валидации на формы" (сложность 2/5)
DieReiterin/middle.game.practicum.yandex pull request #11
Opened 2024-09-27 14:00 UTC by RustamKurbonov

Валидация на полях в форме

2024-09-27 15:11 UTC, MikeDevice requested changes
Хорошая работа! Понравилось, что не дублируешь код.

Что нужно исправить:
1. Валидацию когда пароли не равны
2. Название компонента FullScreenForm.

2024-09-27 15:11 UTC, MikeDevice commented on packages/client/package.json
> +    "@mui/material": "^6.1.1",
Подскажи, пожалуйста, вижу, что `@mui/material` используется в коде, потому понятно, почему ты в dependencies перенёс, а почему `@mui/types`? Не нахожу использования в твоём ПР.

2024-09-27 15:11 UTC, MikeDevice commented on packages/client/src/components/FormField/FormField.module.scss
> +@import '../../assets/styles/vars.scss';
**Заметка:** иногда бесит подключать везде какие-то файлы. Например, переменные часто хочется по дефолту иметь в каждом файле. Это можно сделать, прописав это в конфиг vite. Кому-то нравится, кому-то нет. Просто полезно знать об этом :)

2024-09-27 15:11 UTC, MikeDevice commented on packages/client/src/components/FormField/FormField.tsx
> +}
Круто, что используешь `&` для объединения типов, а не копипастишь!

2024-09-27 15:11 UTC, MikeDevice commented on packages/client/src/components/FormFullScreen/FormFullScreen.tsx
> +export interface FormFullScreenProps {
**Можно лучше:** выше ты используешь для пропсов `type`, а тут `interface`. Хорошо, когда всё в едином стиле, а вообще props всегда описывать через `type`. Это довольно холиварный вопрос. Но я руководстуюсь тем, что редактор кода лучше подсвечивает типы, нежели интерфейсы, потому в таких тривиальных кейсах это лучше.

Полезная статья на эту тему: https://htmlacademy.ru/blog/js/types-vs-interfaces

2024-09-27 15:11 UTC, MikeDevice commented on packages/client/src/components/FormFullScreen/FormFullScreen.tsx
>      </Box>
Расскажи пожалуйста. Вижу, что ты унёс из этого файла компонент `Form`, получается, что название этого файла уже не соответствует действительности (FormFullScreen, но тут нет формы).

**Нужно исправить** название файла или вернуть форму. Так же касается и стиля `{styles.form}`. Его придётся переименовать, если формы тут не будет.

2024-09-27 15:11 UTC, MikeDevice commented on packages/client/src/constants/validation.ts
> +import { FieldValues, Path, RegisterOptions } from 'react-hook-form'
Очень круто, что для всей валидации создан отдельный файл!

2024-09-27 15:11 UTC, MikeDevice commented on packages/client/src/constants/validation.ts
> +}
**Можно лучше:** названия полей не соответствуют действительности. Когда где-то используешь объект `validationMessage`, сложно понять, о чём конкретное сообщение.

**Пример:**
У тебя в коде написано `validationMessage.passwordOk`. И может показаться, что подразумевается, что введён корректный пароль (`От 8 до 40 символов` и тд), но это не так.

2024-09-27 15:11 UTC, MikeDevice commented on packages/client/src/constants/validation.ts
> +    required: true,
**можно лучше:** завести отдельную проверку на `required`, потому что может случиться, что где-то это поле будет обязательным, а где-то нет. но сейчас можно оставить и так.

2024-09-27 15:11 UTC, MikeDevice commented on packages/client/src/constants/validation.ts
> +    pattern: /^(?=.*[A-Z])(?=.*\d).*$/,
Подтверждение моего комментария выше. Эта регулярка проверяет не то, что заложено в сообщении: `Пароли должны совпадать`

2024-09-27 15:11 UTC, MikeDevice commented on packages/client/src/constants/validation.ts
> +  validationScheme[name] as RegisterOptions<TFieldValues, Name>
**Можно лучше:** лучше стараться избегать приведения типов. Тут ситуация не очень простая, потому можешь оставить так, но помни, что `as` это зло.

2024-09-27 15:11 UTC, MikeDevice commented on packages/client/src/pages/Login/Login.tsx
> +interface FormInput {
Выше мой комментарий про то, как описывать пропсы.

2024-09-27 15:11 UTC, MikeDevice commented on packages/client/src/pages/Login/Login.tsx
> +    console.log(data)
Это временное?

2024-09-27 15:32 UTC, RustamKurbonov commented on packages/client/package.json
> +    "@mui/material": "^6.1.1",
Он наверно лишний, уберу

2024-09-27 15:33 UTC, RustamKurbonov commented on packages/client/src/components/FormField/FormField.module.scss
> +@import '../../assets/styles/vars.scss';
Спасибо, круто) буду знать

2024-09-27 15:34 UTC, RustamKurbonov commented on packages/client/src/components/FormFullScreen/FormFullScreen.tsx
> +export interface FormFullScreenProps {
Да, можно попробовать

2024-09-27 15:35 UTC, RustamKurbonov commented on packages/client/src/components/FormFullScreen/FormFullScreen.tsx
>      </Box>
Да, название лучше сменить, согласен

2024-09-27 15:36 UTC, RustamKurbonov commented on packages/client/src/constants/validation.ts
> +}
Да, понял
Переименовать лучше

2024-09-27 15:36 UTC, RustamKurbonov commented on packages/client/src/constants/validation.ts
> +    required: true,
Хорошее замечание

2024-09-27 15:37 UTC, RustamKurbonov commented on packages/client/src/constants/validation.ts
> +    pattern: /^(?=.*[A-Z])(?=.*\d).*$/,
Поправлю

2024-09-27 15:38 UTC, RustamKurbonov commented on packages/client/src/constants/validation.ts
> +  validationScheme[name] as RegisterOptions<TFieldValues, Name>
Да, знаю) тут просто никак не выходило иначе

2024-09-27 15:38 UTC, RustamKurbonov commented on packages/client/src/pages/Login/Login.tsx
> +    console.log(data)
Да, следующей задачей эти данные буду в апи прокидывать

2024-09-27 19:31 UTC, MikeDevice approved these changes
Круто! Молодец, что разобрался с подключением css переменных. 

Ставлю аппрув. Единственное, мне кажется у тебя с зависимостями проблема. 

Ты сейчас удалил руками из package.json либу? yarn.lock не изменился. Удалять либу нужно через команду ярна: `yarn remove <name>`

Но я еще думаю, что все таки эта Люба нужна для каких-то внутренних штук miui фоеймворка.

Можешь просто вернуть эту строку или же удалить эту либу через ярн и проверить, работает ли твой приложение. 

Удачи!

2024-09-28 11:27 UTC, DieReiterin approved these changes
👍 👍

2024-09-28 19:56 UTC, 12rita approved these changes

2024-09-28 19:56 UTC, 12rita commented on packages/client/src/components/Form/Form.tsx
> +  onSubmit?: FormEventHandler<HTMLFormElement>
Точно ли onSubmit опциональный параметр? Дальше он передаётся безусловно

2024-09-28 19:56 UTC, 12rita commented on packages/client/src/components/FormField/FormField.tsx
> +      <Input {...props} inputRef={ref} ref={null} size="small" />
А зачем нужен ref = null?

2024-09-28 19:56 UTC, 12rita commented on packages/client/src/constants/validation.ts
> +export const getValidationScheme = <
Круто описаны дженерики)

2024-09-28 19:56 UTC, 12rita commented on packages/client/vite.config.ts
> +        additionalData: `@import "${path.resolve(
Не знаю, что тут происходит, но выглядит круто :D

2024-09-29 20:51 UTC, RustamKurbonov commented on packages/client/vite.config.ts
> +        additionalData: `@import "${path.resolve(
Теперь в css файлах не надо импортировать vars) он импортится по умолчанию

2024-09-29 20:52 UTC, RustamKurbonov commented on packages/client/src/components/FormField/FormField.tsx
> +      <Input {...props} inputRef={ref} ref={null} size="small" />
Это специфика mui, там ошибка в ref была из за переопределения ref по умолчанию

2024-09-29 20:54 UTC, RustamKurbonov commented on packages/client/src/components/Form/Form.tsx
> +  onSubmit?: FormEventHandler<HTMLFormElement>
Ну это для кейсов, если форма не будет отправляться)
Чисто для отображения 
Или если отправлять форму будем по нажатию по другим кнопкам (не из формы)

2024-09-30 07:54 UTC, merged