Scrum 16
DieReiterin/middle.game.practicum.yandex pull request #16
Opened 2024-10-01 15:10 UTC by itopweb11

### Какую задачу решаем
Scrum 16

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-10-01 22:37 UTC, 12rita approved these changes
Объёмная задача) Пару мелочей можно поправить, но так всё здорово)

2024-10-01 22:37 UTC, 12rita commented on packages/client/src/assets/styles/vars.scss
> +$white: #ffffff;
Вроде, договорились не использовать белый (используем алебастровый)

2024-10-01 22:37 UTC, 12rita commented on packages/client/src/pages/Forum/Forum.module.scss
> +      display: flex;
А чем тут center-flex не подошёл?)

2024-10-01 22:37 UTC, 12rita commented on packages/client/src/pages/Forum/Forum.module.scss
> +      justify-content: space-between;
Аналогично про center-flex)

2024-10-01 22:37 UTC, 12rita commented on packages/client/src/pages/Forum/Forum.tsx
> +    const savedTopics = localStorage.getItem('topics')
круто, что используемся localStorage)

2024-10-01 22:37 UTC, 12rita commented on packages/client/src/pages/Forum/Forum.tsx
> +    if (newTopic.trim() && newDescription.trim()) {
Сейчас не горит, но в будущем, наверное, если предполагается, что оба поля обязательные, то можно, например, дизейблить кнопку создания, пока не все поля заполнены, а то жмакаешь и ничего не происходит)

2024-10-01 22:37 UTC, 12rita commented on packages/client/src/pages/Forum/Forum.tsx
> +      setNewTopic('')
Баг или фича, но если закрыть модалку создания, ничего не сохранив, то при открытии там сохранится то, что мы ввели до этого

2024-10-01 22:37 UTC, 12rita commented on packages/client/src/pages/Forum/Forum.tsx
> +  const [topic, setTopic] = useState<string[]>(() => {
Чисто ради читаемости я бы поменяла на topics, раз уж тут массив)

2024-10-01 22:37 UTC, 12rita commented on packages/client/src/pages/Forum/Forum.tsx
> +              <DeleteIcon style={{ color: '#b0abfe' }} />
Лучше всё же вынести в стили и использовать какую-нибудь константу

2024-10-01 22:37 UTC, 12rita commented on packages/client/src/pages/Forum/Forum.tsx
> +              <div key={index} className={styles.forum__block_contentBlock}>
Лучше не использовать индекс в качестве ключа)

2024-10-01 22:37 UTC, 12rita commented on packages/client/src/pages/Forum/Forum.tsx
> +          <ButtonLink
Супер, что используешь существующий компонент

2024-10-01 22:37 UTC, 12rita commented on packages/client/src/pages/ForumBlockPage/ForumBlockPage.tsx
> +  const handleKeyPress = (event: React.KeyboardEvent<HTMLInputElement>) => {
Круто, что можно добавлять по enter (хотя, возможно, иконочку тоже стоить впихнуть)

2024-10-02 09:55 UTC, RustamKurbonov commented on packages/client/src/pages/Forum/Forum.module.scss
> +@import '@styles/mixins.scss';
Import в scss можно больше не писать - они будут по умолчанию

2024-10-02 09:57 UTC, RustamKurbonov commented on packages/client/src/pages/Forum/Forum.tsx
> +      <div className={styles.forum__block}>
БЭМ - это неплохо, но при модульном css не имеет смысла

2024-10-02 09:57 UTC, RustamKurbonov commented on packages/client/src/pages/Forum/Forum.tsx
> +              <div key={index} className={styles.forum__block_contentBlock}>
зависит от ситуации )

2024-10-02 09:57 UTC, RustamKurbonov commented on packages/client/src/pages/Forum/components/ForumBlock/ForumBlock.module.scss
> +  &__name {}
зачем?)

2024-10-02 09:58 UTC, RustamKurbonov commented on packages/client/src/pages/Forum/components/ForumBlock/ForumBlock.tsx
> +    <div className={styles.forumBlock} onClick={onClick}>
по семантике на div click вешать нельзя, используй кнопку

2024-10-02 10:28 UTC, DieReiterin reviewed
Работа проделана очень большая, видно хорошее качество стилей и компонентов 👍 
Однако нужно проверить, что она соответствует задаче, и ещё исправить пару моментов - вся инфа внизу🔽

2024-10-02 10:28 UTC, Verdunner commented on packages/client/src/pages/Forum/Forum.tsx
> +              <div key={index} className={styles.forum__block_contentBlock}>
Наверно, это временное решение - в будущем при работе с апи форума будем использовать id топика в качестве ключа

2024-10-02 10:28 UTC, Verdunner commented on packages/client/src/pages/Forum/Forum.tsx
> +                  messages={index + 5}
Также количество тредов и сообщений лучше вывести в state/memo, поскольку они будут загружаться по апи

2024-10-02 10:28 UTC, Verdunner commented on packages/client/src/pages/ForumBlockPage/ForumBlockPage.module.scss
> +.forumBlock {
Лучше сразу переименовать стили, чтобы было как на остальных страницах (без camelCase)

2024-10-02 10:28 UTC, DieReiterin commented on packages/client/src/pages/Forum/components/ForumModal/ForumModal.tsx
Возможно, лучше сделать так, чтобы в src/components лежал общий компонент модального окна, и его везде использовать?

2024-10-02 10:28 UTC, DieReiterin commented on packages/client/src/pages/ForumBlockPage/ForumBlockPage.tsx
> +  }
Отличный приём 👍

2024-10-02 10:28 UTC, DieReiterin commented on packages/client/src/pages/ForumBlockPage/ForumBlockPage.tsx
Я не вижу, учёл ли ты этот момент, но комментарии и темы не принадлежат одному человеку - у всех свой id, и поле "автор". 
В будущем, когда подключим апи форума, порядок работы будет такой:

- Мы заходим на страницу форума, делаем запрос, загружаем список тем (топиков/тредов)
Темы могут быть как наши, так и не наши

- мы можем добавить новую тему, через запрос на сервер

- мы можем открыть одну из тем и загрузить сообщения (комменты) из неё - сообщения могут быть наши или не наши (у каждого свой автор)

- Мы можем перейти назад к списку тем

2024-10-02 11:19 UTC, itopweb11 commented on packages/client/src/pages/Forum/Forum.tsx
> +              <div key={index} className={styles.forum__block_contentBlock}>
это временное решение

2024-10-02 11:50 UTC, itopweb11 commented on packages/client/src/pages/Forum/Forum.tsx
> +                  messages={index + 5}
это временное решение

2024-10-02 15:02 UTC, itopweb11 commented on packages/client/src/pages/ForumBlockPage/ForumBlockPage.tsx
Я пока что добавил страницы и реализовал небольшой функционал. В будущем, когда API будет готово, почти весь функционал придется переделать.

2024-10-02 15:03 UTC, itopweb11 commented on packages/client/src/pages/Forum/Forum.module.scss
> +      display: flex;
исправил

2024-10-02 15:04 UTC, itopweb11 commented on packages/client/src/pages/Forum/Forum.module.scss
> +      justify-content: space-between;
исправил

2024-10-02 15:04 UTC, itopweb11 commented on packages/client/src/pages/Forum/Forum.tsx
> +    if (newTopic.trim() && newDescription.trim()) {
исправил

2024-10-02 15:04 UTC, itopweb11 commented on packages/client/src/pages/Forum/Forum.tsx
> +  const [topic, setTopic] = useState<string[]>(() => {
исправил

2024-10-02 15:04 UTC, itopweb11 commented on packages/client/src/pages/Forum/Forum.tsx
> +              <DeleteIcon style={{ color: '#b0abfe' }} />
исправил

2024-10-02 15:04 UTC, itopweb11 commented on packages/client/src/pages/ForumBlockPage/ForumBlockPage.tsx
> +  const handleKeyPress = (event: React.KeyboardEvent<HTMLInputElement>) => {
исправил

2024-10-02 15:06 UTC, itopweb11 commented on packages/client/src/pages/Forum/Forum.module.scss
> +@import '@styles/mixins.scss';
если не писать Import в scss то выдаёт ошибку , пока решил оставить так

2024-10-02 15:08 UTC, itopweb11 commented on packages/client/src/pages/Forum/components/ForumBlock/ForumBlock.module.scss
> +  &__name {}
исправил

2024-10-02 15:08 UTC, itopweb11 commented on packages/client/src/pages/Forum/components/ForumBlock/ForumBlock.tsx
> +    <div className={styles.forumBlock} onClick={onClick}>
исправил

2024-10-02 15:08 UTC, itopweb11 commented on packages/client/src/pages/ForumBlockPage/ForumBlockPage.module.scss
> +.forumBlock {
исправил

2024-10-02 15:12 UTC, itopweb11 commented on packages/client/src/pages/Forum/components/ForumModal/ForumModal.tsx
похожей модалки в проекте не нашёл поэтому нету смысла вынести его отдельно

2024-10-03 08:00 UTC, DieReiterin approved these changes

2024-10-03 08:00 UTC, Verdunner commented on packages/client/src/pages/ForumBlockPage/ForumBlockPage.module.scss
> +    align-items: end;
Вместо start и end лучше использовать flex-start и flex-end

![flex-end](https://github.com/user-attachments/assets/c27baa3c-3902-4bcd-b110-f89c85160bcf)

2024-10-03 08:00 UTC, Verdunner commented on packages/client/src/pages/ForumBlockPage/ForumBlockPage.module.scss
>      width: 100%;
Я плохо обьяснил что имел в виду. В моем комментарии по поводу названий твоих стилей, я хотел сказать:

- обычно используется именование БЭМ -- например .forum-block { &__button-home {...} }

- но у нас в проекте БЭМ не нужен (так как используются файлы типа *.module.css)

- поэтому мы используем для классов одно слово или два слова через camelCase -- например wrapper, forumBlock или buttonHome

- при этом мы не используем вложенность scss - классы идут один за другим, а не вкладываются через &__buttonHome {...}

Ниже пример как правильно (файл Main.module.scss)

![classes](https://github.com/user-attachments/assets/4e7a762a-85ce-493b-bbd5-1538ded6635d)

2024-10-03 08:00 UTC, Verdunner commented on packages/client/src/pages/ForumBlockPage/ForumBlockPage.tsx
Ты уже сделал очень большую задачу, и я бы хотел чтобы ты её поскорее сдал, получил зачёт за 5 спринт и пошел дальше
Но мне кажется, что даже заготовка форума (страницы и небольшой функционал) должна быть заранее готова к добавлению АПИ без переделывания всего функционала
В восьмом спринте будет большая задача на добавление АПИ форума, и тому кто её возьмёт, будет неудобно - придётся дополнительно переделывать функционал страниц (доделывать за тобой)

Я предлагаю выбрать один из вариантов:
- подумать над тем, как должен правильно работать форум и переделать функционал сейчас
- не переделывать, сдать зачёт, и в будущем взять задачу на добавление АПИ форума

2024-10-03 08:47 UTC, itopweb11 commented on packages/client/src/assets/styles/vars.scss
> +$white: #ffffff;
исправил

2024-10-03 08:47 UTC, itopweb11 commented on packages/client/src/pages/Forum/Forum.tsx
> +      setNewTopic('')
исправил

2024-10-03 10:01 UTC, DieReiterin approved these changes

2024-10-03 12:14 UTC, itopweb11 commented on packages/client/src/pages/ForumBlockPage/ForumBlockPage.tsx
1

2024-10-03 12:16 UTC, itopweb11 commented on packages/client/src/pages/ForumBlockPage/ForumBlockPage.module.scss
> +    align-items: end;
исправил

2024-10-03 12:55 UTC, itopweb11 commented on packages/client/src/pages/ForumBlockPage/ForumBlockPage.module.scss
>      width: 100%;
исправил

2024-10-03 12:55 UTC, itopweb11 commented on packages/client/src/pages/Forum/Forum.tsx
> +      <div className={styles.forum__block}>
исправил

2024-10-03 15:10 UTC, DieReiterin approved these changes

2024-10-03 15:59 UTC, DieReiterin approved these changes

2024-10-03 18:32 UTC, RustamKurbonov approved these changes
Все хорошо 👌

2024-10-04 07:53 UTC, DieReiterin approved these changes

2024-10-04 10:43 UTC, MikeDevice requested changes
Большая работа проделана. Ты молодец! Есть пару критичных замечаний, которые нужно исправить и побольше улучшений, с которыми можешь просто ознакомиться.

2024-10-04 10:43 UTC, MikeDevice commented on package-lock.json
Хм, хм, хм. Странно, что у вас в проекте и package.lock и yarn.lock. Должно быть что-то одно и скорее всего это yarn.lock. Видно, кто-то у вас ставит зависимости через npm install, а кто-то через yarn

2024-10-04 10:43 UTC, MikeDevice commented on packages/client/src/assets/images/photo-1-720.jpg
**Можно лучше:** есть правило хорошего тона: везде подключать две и более картинок:

Оригинальная — эта.
2х — в два раза больше (для айфонов и макбуков, они требуют более крупного разрешения)
3х — редко (для особенных телефонов)
4х — так же.
Если интересно, вот тут есть подробное описание этого процесса
https://htmlacademy.ru/blog/html/retina

2024-10-04 10:43 UTC, MikeDevice commented on packages/client/src/assets/styles/mixins.scss
> +
Круто! Часто приходится писать такое. Молодец!

2024-10-04 10:43 UTC, MikeDevice commented on packages/client/src/pages/Forum/Forum.module.scss
> +}
писать стили для тегов — плохой тон. Это можно делать, но, например, когда тебе нужно стилизовать библиотеку, к коду которой у тебя нет доступа. Я понимаю, что ты обернул это всё в `.forumBlockHeaderBlock`, но всё равно это сомнительная история.

Не буду реджектить за это, но рекомендую не злоупотребять этим.

2024-10-04 10:43 UTC, MikeDevice commented on packages/client/src/pages/Forum/Forum.tsx
> +    return savedTopics ? JSON.parse(savedTopics) : []
**Можно лучше:** Сейчас ты достаёшь данные из локального хранилища. Но в будущем ты будешь доставать из бд или ещё откуда-то и тебе придётся менять этот компонент, а если бы эти данные использовались в нескольких компонентах, то все их. 

Потому считается хорошим тоном — выносить такой код из реакт компонента. В данном случае самое место для этого — это редаксовый thunk.

2024-10-04 10:43 UTC, MikeDevice commented on packages/client/src/pages/Forum/Forum.tsx
> +      localStorage.setItem('topics', JSON.stringify(updatedTopics))
**можно лучше:** то же, что и выше — логика сохранения данных и логика отрисовки визуала — это разные уровни кода, потому желательно их не смешивать.

2024-10-04 10:43 UTC, MikeDevice commented on packages/client/src/pages/Forum/Forum.tsx
> +    navigate(`${PathsRoutes.Forum}/${index + 1}`, { state: topicData })
**исправить:** вот это не есть хорошо. ты здесь завязываешься на индекс, и велика вероятность, что тут всё разломается, если данные изменятся, например, удалится один элемент, то навигация сломается.

Нужно, чтобы у каждого топика был свой `id`, и тут использовать только `id`.

2024-10-04 10:43 UTC, MikeDevice commented on packages/client/src/pages/Forum/Forum.tsx
> +    const updatedTopics = topics.filter((_, i) => i !== index)
**исправить:** тут тоже надо с id работать

2024-10-04 10:43 UTC, MikeDevice commented on packages/client/src/pages/Forum/Forum.tsx
> +            }
**Надо исправить**: тут две проблемы:
1. в реакт вёрстке так писать не нужно. принято, что все вычисления выносятся вверх компонента (до return). Это позволяет сохранять чистоту кода и отлов дальнейших ошибок.
2. **можно лучше:** `JSON.parse` очень тяжёлая операция. рекомендую перед return делать `JSON.parse` для `topics`, а не для каждого топика в отдельности

2024-10-04 10:43 UTC, MikeDevice commented on packages/client/src/pages/Forum/Forum.tsx
> +                  messages={index + 5}
**исправить:**

1. то, что я выше писал про индексы.
2. цифра 5 максимально неинформативная. Любой другой, глядя на этот код может трактовать её по своему, оттого высока вероятность сделать ошибку.

2024-10-04 10:43 UTC, MikeDevice commented on packages/client/src/pages/Forum/Forum.tsx
> +              margin: '10px',
**можно лучше** стили лучше добавлять через className, так как так проще их менять в дальнейшем, да и загрузка кода в браузер так идёт быстрее.

2024-10-04 10:43 UTC, MikeDevice commented on packages/client/src/pages/Forum/components/ForumModal/ForumModal.module.scss
> +  h3 {
**исправить:** я выше писал, что не буду реджектить из-за стилей тегов, так как думал, что это единственный и безысходный случай. Но вижу, что это не так, потому исправь все стили тегов, добавив им `className`

2024-10-04 10:43 UTC, MikeDevice commented on packages/client/src/pages/ForumBlockPage/ForumBlockPage.tsx
> +    return savedComments ? JSON.parse(savedComments) : []
**можно лучше:** см. комментарий выше про вынос получения данных в другой файл

2024-10-04 10:43 UTC, MikeDevice commented on packages/client/src/pages/ForumBlockPage/components/ForumMessage/ForumMessage.tsx
> +  }
**Исправить:** тут копируется логика с файлов выше, потому вынеси её в хук и используй его в этих двух местах.

2024-10-04 10:43 UTC, MikeDevice commented on packages/client/src/pages/ForumBlockPage/components/ForumMessage/ForumMessage.tsx
> +            {comments.map((c, index) => (
**можно лучше:** однобуквенные переменные лучше всего использовать только для индексов, потому иначе очень сложно понять, что внутри. Тут лучше использовать `comment`

2024-10-04 15:08 UTC, itopweb11 commented on packages/client/src/pages/Forum/Forum.module.scss
> +}
исправил

2024-10-06 14:01 UTC, itopweb11 commented on packages/client/src/pages/Forum/Forum.tsx
> +    navigate(`${PathsRoutes.Forum}/${index + 1}`, { state: topicData })
исправил

2024-10-06 14:03 UTC, itopweb11 commented on packages/client/src/pages/Forum/Forum.tsx
> +    const updatedTopics = topics.filter((_, i) => i !== index)
исправил

2024-10-06 14:08 UTC, itopweb11 commented on packages/client/src/pages/Forum/Forum.tsx
> +            }
исправил

2024-10-06 14:23 UTC, itopweb11 commented on packages/client/src/pages/Forum/Forum.tsx
> +                  messages={index + 5}
исправил 

Но не знаю ка получить количество сообщений топика в компоненте Forum

2024-10-06 14:32 UTC, itopweb11 commented on packages/client/src/pages/Forum/Forum.tsx
> +              margin: '10px',
исправил

2024-10-06 14:32 UTC, itopweb11 commented on packages/client/src/pages/Forum/components/ForumModal/ForumModal.module.scss
> +  h3 {
исправил

2024-10-06 15:04 UTC, itopweb11 commented on packages/client/src/pages/ForumBlockPage/components/ForumMessage/ForumMessage.tsx
> +  }
исправил

2024-10-06 15:05 UTC, itopweb11 commented on packages/client/src/pages/Forum/Forum.module.scss
> +}
исправил

2024-10-06 15:06 UTC, itopweb11 commented on packages/client/src/pages/ForumBlockPage/components/ForumMessage/ForumMessage.tsx
> +            {comments.map((c, index) => (
исправил

2024-10-07 07:49 UTC, DieReiterin approved these changes

2024-10-07 09:00 UTC, MikeDevice approved these changes
Есть некоторые замечания по поводу JSON.parse и id вместо индексов, а так молодец, что всё исправил!

2024-10-07 09:00 UTC, MikeDevice commented on packages/client/src/hooks/useTopicData.ts
> +  const topicData = location.state
Тут не совсем корректно. Ты тут, получается, всё состояние url именуешь, как топик дата, но это будет работать только в частном только твоём случае. Немного изменится кодовая база и это уже будет не соответствовать действительности.

2024-10-07 09:00 UTC, MikeDevice commented on packages/client/src/pages/Forum/Forum.tsx
> +        id: Date.now(),
этот вариант как временный имеет место быть, но лучше всего для таких нужд использовать более надёжные способы, как вот это, например: https://github.com/ai/nanoid

2024-10-07 09:00 UTC, MikeDevice commented on packages/client/src/hooks/useTopicData.ts
> +  const topicData = location.state
лучше, чтобы в state был объект, у которого было бы поле `topicData`

2024-10-07 09:00 UTC, MikeDevice commented on packages/client/src/pages/Forum/Forum.tsx
> +    const updatedTopics = topics.filter(t => JSON.parse(t).id !== id)
**можно лучше:** сделай JSON.parse для всех топиков в самом начале компонента всего один раз и сохрани в переменную. А потом просто используй эту переменную. так будет проще.

2024-10-07 09:00 UTC, MikeDevice commented on packages/client/src/pages/Forum/Forum.tsx
> +  const parsedTopics = topics.map(t => JSON.parse(t))
и это тогда уйдёт

2024-10-07 12:26 UTC, merged