Добавить Service Workers (офлайн-режим приложения) (сложность 2/5)
DieReiterin/middle.game.practicum.yandex pull request #21
Opened 2024-10-07 13:49 UTC by 12rita

### Какую задачу решаем
Добавила sw
Работала с этим первый раз, так что комментарии по улучшению приветствуются) 
Попыталась сделать франкенштейна из теории в практикуме и статьи на хабре: если данные есть в кеше, то они оттуда отдаются, но всё равно делается fetch в фоне, чтобы актуализировать данные. Если их нет, то просто фетчим
Как можно проверить: запустить приложение, а потом остановить сервер. Приложенька всё ещё будет открываться + в Application -> cacheStorage валяются файлики

2024-10-07 15:39 UTC, DieReiterin approved these changes
Всё очень изящно и красиво :sparkles: можно только поправить пару моментов

2024-10-07 15:39 UTC, DieReiterin commented on packages/client/sw.js
> +      })
Тут может упасть SW на установке - я бы тут не выбрасывал ошибку, а залогировал: console.error('Failed to cache resources', err)

2024-10-07 15:39 UTC, DieReiterin commented on packages/client/sw.js
> +  })
Тут тоже не совсем ясно, куда "отправлена" ошибка - я бы посоветовал сделать так:
```javascript
.catch(err => {
  console.error('Fetch failed:', err)
  return caches.match('/fallback.html') // для странички с ошибкой
})
```

2024-10-07 15:39 UTC, DieReiterin commented on packages/client/sw.js
> +      )
Насколько я понимаю, тут опечатка в методе фильтра :grimacing: 
если оставить так, мы будем удалять тут только правильный кеш

2024-10-07 22:07 UTC, 12rita commented on packages/client/sw.js
> +  })
Ошибка отправится как обычный результат fetch 
То есть тут, насколько я понимаю, может любой запрос упасть, необязательно из-за отсутсnвия чего-то в кеше, поэтому fallback не всегда актуален
Добавила вывод в консоль

2024-10-07 22:08 UTC, 12rita commented on packages/client/sw.js
> +      )
Да, вроде, я преполагала, что тут кеш очищается) 
![image](https://github.com/user-attachments/assets/5dce6e0d-a5bc-4100-a895-6c07cf4c2abd)

2024-10-08 07:40 UTC, DieReiterin approved these changes

2024-10-08 15:30 UTC, kyzinatra commented on packages/client/sw.js
> +
Надо исправить: ваш браузер не может видить и парсить `ts, tsx` файлы. Все они компилируются в `js`. Именно их надо сохранять. Для того, чтобы получить все пути и названия необходимо при билде написать скрипт, который пройдет на `assets` и возьмет все названия с хэшами. Можете использовать для этого готовые инструменты

2024-10-08 15:31 UTC, kyzinatra commented on packages/client/sw.js
> +          void update(fetchRequest)
Можно лучше: не стоит вводить кэширование для всех запросов. Стоит выделить конкретные запросы которые надо кэшировать и вписать только их. А к примеру POST запросы пропускать мимо кэша вообще

2024-10-08 15:33 UTC, kyzinatra requested changes
Отличная работа! Вы отлично справились с настройкой сервис воркеров, но сейчас есть несколько проблем с ними. Я предлагаю вам посмотреть, как работают готовые иснтументы вроде workbox и сделать похожие воркры у себя. Важно чтобы воркеры не мешали работе сайта и кэшировали правильные файлы

2024-10-08 15:36 UTC, 12rita commented on packages/client/sw.js
> +
У меня был связанный с этим вопрос: нужно ли пытаться закешировать бандл, который в итоге собирает вебпак? Или это вообще что-то мимо? Не смогла найти в интернете нормального объяснения

2024-10-08 15:53 UTC, kyzinatra commented on packages/client/sw.js
> +
Кроме бандла у вас на фронте ничего нет, так что именно бандл только и можно кэшировать

2024-10-08 20:43 UTC, 12rita commented
> Отличная работа! Вы отлично справились с настройкой сервис воркеров, но сейчас есть несколько проблем с ними. Я предлагаю вам посмотреть, как работают готовые иснтументы вроде workbox и сделать похожие воркры у себя. Важно чтобы воркеры не мешали работе сайта и кэшировали правильные файлы

Попыталась переделать логику, использовав плагин для vite и workbox, но дебажить стало сложнее) При сборке, вроде, кеш собирается
Ещё вопрос, почему в начальной версии работало?)

2024-10-08 20:55 UTC, kyzinatra commented
> > Отличная работа! Вы отлично справились с настройкой сервис воркеров, но сейчас есть несколько проблем с ними. Я предлагаю вам посмотреть, как работают готовые иснтументы вроде workbox и сделать похожие воркры у себя. Важно чтобы воркеры не мешали работе сайта и кэшировали правильные файлы
> 
> Попыталась переделать логику, использовав плагин для vite и workbox, но дебажить стало сложнее) При сборке, вроде, кеш собирается Ещё вопрос, почему в начальной версии работало?)

Работало потому что кэш собирался через fetch обработчик, так как на него нет никаких ограничений он и статику кэширует, но там именно делать не очень хорошо. Ее стоит кэшировать на install

2024-10-09 06:40 UTC, kyzinatra commented on packages/client/vite.config.ts
> +        type: 'module',
dev стоит уключать условно `process.env === "devolopment"`

2024-10-09 06:41 UTC, kyzinatra approved these changes
Вы отлично потрудились.
Поздравляю! Ваша работа принята.
Удачного дальнейшего обучения.

2024-10-09 08:53 UTC, itopweb11 approved these changes

2024-10-09 08:55 UTC, merged